# Minecraft Server Properties (Optimized for High Performance)
server-port=25565
server-ip=
enable-rcon=false
motd=\u00A7a24/7 High-Performance Minecraft Server \u00A7r[\u00A7bElite Club SMP\u00A7r]
max-players=20
view-distance=10
simulation-distance=6
online-mode=false
allow-flight=true
pvp=true
difficulty=normal
gamemode=survival
spawn-protection=0
enable-command-block=true
enforce-secure-profile=false
sync-chunk-writes=false
